//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.svcPlanetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcPlanetService.IPlanetService")]
    public interface IPlanetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanetService/GetOrphanPlanets", ReplyAction="http://tempuri.org/IPlanetService/GetOrphanPlanetsResponse")]
        int GetOrphanPlanets(Planet_DTO.PlanetsInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanetService/GetOrphanPlanets", ReplyAction="http://tempuri.org/IPlanetService/GetOrphanPlanetsResponse")]
        System.Threading.Tasks.Task<int> GetOrphanPlanetsAsync(Planet_DTO.PlanetsInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanetService/GetHottestPlanet", ReplyAction="http://tempuri.org/IPlanetService/GetHottestPlanetResponse")]
        string GetHottestPlanet(Planet_DTO.PlanetsInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanetService/GetHottestPlanet", ReplyAction="http://tempuri.org/IPlanetService/GetHottestPlanetResponse")]
        System.Threading.Tasks.Task<string> GetHottestPlanetAsync(Planet_DTO.PlanetsInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanetService/GetPlanetTimelineByYearandSize", ReplyAction="http://tempuri.org/IPlanetService/GetPlanetTimelineByYearandSizeResponse")]
        Planet_DTO.PlanetsTimeline[] GetPlanetTimelineByYearandSize(Planet_DTO.PlanetsInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanetService/GetPlanetTimelineByYearandSize", ReplyAction="http://tempuri.org/IPlanetService/GetPlanetTimelineByYearandSizeResponse")]
        System.Threading.Tasks.Task<Planet_DTO.PlanetsTimeline[]> GetPlanetTimelineByYearandSizeAsync(Planet_DTO.PlanetsInfo value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlanetServiceChannel : WebApplication5.svcPlanetService.IPlanetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlanetServiceClient : System.ServiceModel.ClientBase<WebApplication5.svcPlanetService.IPlanetService>, WebApplication5.svcPlanetService.IPlanetService {
        
        public PlanetServiceClient() {
        }
        
        public PlanetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlanetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetOrphanPlanets(Planet_DTO.PlanetsInfo value) {
            return base.Channel.GetOrphanPlanets(value);
        }
        
        public System.Threading.Tasks.Task<int> GetOrphanPlanetsAsync(Planet_DTO.PlanetsInfo value) {
            return base.Channel.GetOrphanPlanetsAsync(value);
        }
        
        public string GetHottestPlanet(Planet_DTO.PlanetsInfo value) {
            return base.Channel.GetHottestPlanet(value);
        }
        
        public System.Threading.Tasks.Task<string> GetHottestPlanetAsync(Planet_DTO.PlanetsInfo value) {
            return base.Channel.GetHottestPlanetAsync(value);
        }
        
        public Planet_DTO.PlanetsTimeline[] GetPlanetTimelineByYearandSize(Planet_DTO.PlanetsInfo value) {
            return base.Channel.GetPlanetTimelineByYearandSize(value);
        }
        
        public System.Threading.Tasks.Task<Planet_DTO.PlanetsTimeline[]> GetPlanetTimelineByYearandSizeAsync(Planet_DTO.PlanetsInfo value) {
            return base.Channel.GetPlanetTimelineByYearandSizeAsync(value);
        }
    }
}
